language: node_js

node_js:
  - "stable"

sudo: false

before_install:
  # https://github.com/npm/npm/issues/11283
  - npm set progress=false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
